// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/services/factors/factors.proto

package factors

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FactorsService_GetFactor_FullMethodName = "/factors.FactorsService/GetFactor"
)

// FactorsServiceClient is the client API for FactorsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FactorsServiceClient interface {
	GetFactor(ctx context.Context, in *FactorRequest, opts ...grpc.CallOption) (*FactorResponse, error)
}

type factorsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFactorsServiceClient(cc grpc.ClientConnInterface) FactorsServiceClient {
	return &factorsServiceClient{cc}
}

func (c *factorsServiceClient) GetFactor(ctx context.Context, in *FactorRequest, opts ...grpc.CallOption) (*FactorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactorResponse)
	err := c.cc.Invoke(ctx, FactorsService_GetFactor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FactorsServiceServer is the server API for FactorsService service.
// All implementations must embed UnimplementedFactorsServiceServer
// for forward compatibility.
type FactorsServiceServer interface {
	GetFactor(context.Context, *FactorRequest) (*FactorResponse, error)
	mustEmbedUnimplementedFactorsServiceServer()
}

// UnimplementedFactorsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFactorsServiceServer struct{}

func (UnimplementedFactorsServiceServer) GetFactor(context.Context, *FactorRequest) (*FactorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFactor not implemented")
}
func (UnimplementedFactorsServiceServer) mustEmbedUnimplementedFactorsServiceServer() {}
func (UnimplementedFactorsServiceServer) testEmbeddedByValue()                        {}

// UnsafeFactorsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FactorsServiceServer will
// result in compilation errors.
type UnsafeFactorsServiceServer interface {
	mustEmbedUnimplementedFactorsServiceServer()
}

func RegisterFactorsServiceServer(s grpc.ServiceRegistrar, srv FactorsServiceServer) {
	// If the following call pancis, it indicates UnimplementedFactorsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FactorsService_ServiceDesc, srv)
}

func _FactorsService_GetFactor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactorsServiceServer).GetFactor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FactorsService_GetFactor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactorsServiceServer).GetFactor(ctx, req.(*FactorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FactorsService_ServiceDesc is the grpc.ServiceDesc for FactorsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FactorsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "factors.FactorsService",
	HandlerType: (*FactorsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFactor",
			Handler:    _FactorsService_GetFactor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/services/factors/factors.proto",
}
