// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/services/factors/factors.proto

package factors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorRequest) Reset() {
	*x = FactorRequest{}
	mi := &file_pkg_services_factors_factors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorRequest) ProtoMessage() {}

func (x *FactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_factors_factors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorRequest.ProtoReflect.Descriptor instead.
func (*FactorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_services_factors_factors_proto_rawDescGZIP(), []int{0}
}

func (x *FactorRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type FactorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorResponse) Reset() {
	*x = FactorResponse{}
	mi := &file_pkg_services_factors_factors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorResponse) ProtoMessage() {}

func (x *FactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_factors_factors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorResponse.ProtoReflect.Descriptor instead.
func (*FactorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_services_factors_factors_proto_rawDescGZIP(), []int{1}
}

func (x *FactorResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_pkg_services_factors_factors_proto protoreflect.FileDescriptor

const file_pkg_services_factors_factors_proto_rawDesc = "" +
	"\n" +
	"\"pkg/services/factors/factors.proto\x12\afactors\"'\n" +
	"\rFactorRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\"&\n" +
	"\x0eFactorResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value2N\n" +
	"\x0eFactorsService\x12<\n" +
	"\tGetFactor\x12\x16.factors.FactorRequest\x1a\x17.factors.FactorResponseB\x12Z\x10services/factorsb\x06proto3"

var (
	file_pkg_services_factors_factors_proto_rawDescOnce sync.Once
	file_pkg_services_factors_factors_proto_rawDescData []byte
)

func file_pkg_services_factors_factors_proto_rawDescGZIP() []byte {
	file_pkg_services_factors_factors_proto_rawDescOnce.Do(func() {
		file_pkg_services_factors_factors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_services_factors_factors_proto_rawDesc), len(file_pkg_services_factors_factors_proto_rawDesc)))
	})
	return file_pkg_services_factors_factors_proto_rawDescData
}

var file_pkg_services_factors_factors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_services_factors_factors_proto_goTypes = []any{
	(*FactorRequest)(nil),  // 0: factors.FactorRequest
	(*FactorResponse)(nil), // 1: factors.FactorResponse
}
var file_pkg_services_factors_factors_proto_depIdxs = []int32{
	0, // 0: factors.FactorsService.GetFactor:input_type -> factors.FactorRequest
	1, // 1: factors.FactorsService.GetFactor:output_type -> factors.FactorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_services_factors_factors_proto_init() }
func file_pkg_services_factors_factors_proto_init() {
	if File_pkg_services_factors_factors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_services_factors_factors_proto_rawDesc), len(file_pkg_services_factors_factors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_services_factors_factors_proto_goTypes,
		DependencyIndexes: file_pkg_services_factors_factors_proto_depIdxs,
		MessageInfos:      file_pkg_services_factors_factors_proto_msgTypes,
	}.Build()
	File_pkg_services_factors_factors_proto = out.File
	file_pkg_services_factors_factors_proto_goTypes = nil
	file_pkg_services_factors_factors_proto_depIdxs = nil
}
