// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/services/calculator/calculator.proto

package calculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_pkg_services_calculator_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_calculator_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pkg_services_calculator_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Request) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Request) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_services_calculator_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_services_calculator_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_services_calculator_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_pkg_services_calculator_calculator_proto protoreflect.FileDescriptor

const file_pkg_services_calculator_calculator_proto_rawDesc = "" +
	"\n" +
	"(pkg/services/calculator/calculator.proto\x12\n" +
	"calculator\"=\n" +
	"\aRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2\xe8\x01\n" +
	"\x11CalculatorService\x120\n" +
	"\x03Sum\x12\x13.calculator.Request\x1a\x14.calculator.Response\x123\n" +
	"\x06Divide\x12\x13.calculator.Request\x1a\x14.calculator.Response\x125\n" +
	"\bMultiply\x12\x13.calculator.Request\x1a\x14.calculator.Response\x125\n" +
	"\bSubtract\x12\x13.calculator.Request\x1a\x14.calculator.ResponseB\x15Z\x13services/calculatorb\x06proto3"

var (
	file_pkg_services_calculator_calculator_proto_rawDescOnce sync.Once
	file_pkg_services_calculator_calculator_proto_rawDescData []byte
)

func file_pkg_services_calculator_calculator_proto_rawDescGZIP() []byte {
	file_pkg_services_calculator_calculator_proto_rawDescOnce.Do(func() {
		file_pkg_services_calculator_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_services_calculator_calculator_proto_rawDesc), len(file_pkg_services_calculator_calculator_proto_rawDesc)))
	})
	return file_pkg_services_calculator_calculator_proto_rawDescData
}

var file_pkg_services_calculator_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_services_calculator_calculator_proto_goTypes = []any{
	(*Request)(nil),  // 0: calculator.Request
	(*Response)(nil), // 1: calculator.Response
}
var file_pkg_services_calculator_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.CalculatorService.Sum:input_type -> calculator.Request
	0, // 1: calculator.CalculatorService.Divide:input_type -> calculator.Request
	0, // 2: calculator.CalculatorService.Multiply:input_type -> calculator.Request
	0, // 3: calculator.CalculatorService.Subtract:input_type -> calculator.Request
	1, // 4: calculator.CalculatorService.Sum:output_type -> calculator.Response
	1, // 5: calculator.CalculatorService.Divide:output_type -> calculator.Response
	1, // 6: calculator.CalculatorService.Multiply:output_type -> calculator.Response
	1, // 7: calculator.CalculatorService.Subtract:output_type -> calculator.Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_services_calculator_calculator_proto_init() }
func file_pkg_services_calculator_calculator_proto_init() {
	if File_pkg_services_calculator_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_services_calculator_calculator_proto_rawDesc), len(file_pkg_services_calculator_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_services_calculator_calculator_proto_goTypes,
		DependencyIndexes: file_pkg_services_calculator_calculator_proto_depIdxs,
		MessageInfos:      file_pkg_services_calculator_calculator_proto_msgTypes,
	}.Build()
	File_pkg_services_calculator_calculator_proto = out.File
	file_pkg_services_calculator_calculator_proto_goTypes = nil
	file_pkg_services_calculator_calculator_proto_depIdxs = nil
}
